spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/blog_htz?useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: 123456
    druid:
      #   数据源其他配置
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null

  #出现错误时, 直接抛出异常
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    #restFul风格: 不要为资源文件建立映射
    add-mappings: false
    static-locations:

  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages #国际化
  profiles:
    active: pro

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.htz.blog.po

# pagehelper
pagehelper:
  helperDialect: mysql #指定数据库
  reasonable: true #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。
                   #禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  supportMethodsArguments: true #是否支持接口参数来传递分页参数，默认false
  params: count=countSql

# 阿里云对象存储服务配置
aliyun:
  oss:
    accessKeyId: *
    accessKeySecret: *
    endpoint: *
    bucketName: *
    webUrl: *


comment.avatar: /images/avatar.jpg  #游客默认头像
logging:
  level:
    root: info #设置全局日志级别，此处默认为info,生产环境可设置为更高级别的warn
    cn.htz.blog: debug #指定对应目录的日志级别，在此目录内的日志级别为debug

  file:
    path: log/blog-dev.log
