spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://emysql/blog_htz
    url: jdbc:mysql://47.98.221.67:3306/blog_htz
    username: root
    password: 123456
server:
  port: 8888
#  port: 80